name: release
on:

  push:
    branches:
      - main
      - develop
      - master


env:
  BASE_DIR: "."
  NODE_VERSION: "14"
  JAVA_VERSION: "11"
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
          ${{ runner.os }}-maven-
      - name: mvn verify
        run: mvn -B verify --file pom.xml
        working-directory: ${{ env.BASE_DIR }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
          ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm cache clean --force && npm install
      - name: Install dependencies2
        run: npm ci
      - name: release all the things
        run: |
        npx multi-semantic-release --execasync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
